### ISSUE TITLE
Method to get number of read parsed bytes

### ISSUE THREAD

**Issue by lud4ik** [gwenn/yacr#3]
I mean if it read 4096, but records read occupy 3000, it should return 3000.

**Comment by gwenn** [comment]
I think you can do it by keeping track on the total number of bytes read [here](https://github.com/gwenn/yacr/blob/master/reader.go#L259).
Something like:
```go
nBytes += a // where nBytes is a new field of Reader 
```

**Comment by gwenn** [comment]
Do you mind telling me if you solved your problem ?
